In [30]:
def entire(func):
    def inner_func(*args, **kwargs):
        print('first')
        result = func(*args, **kwargs)
        print('second')
        return result
    return inner_func

In [31]:
@entire
def qwer(a,b):
    print(a+b)
    return a+b

In [32]:
qwer(1,2)

first
3
second


3

In [1]:
import numpy as np

In [6]:
array = np.array([0, 1, 2, 3, 4, 5])
print(array)
print(np.split(array,[2]))
print(array)

[0 1 2 3 4 5]
[array([0, 1]), array([2, 3, 4, 5])]
[0 1 2 3 4 5]


In [7]:
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [9]:
np.unique(np.linspace(0, 10, 5),return_counts=True)

(array([  0. ,   2.5,   5. ,   7.5,  10. ]),
 array([1, 1, 1, 1, 1], dtype=int64))

In [15]:
A = np.linspace(0,10,5)
B = np.array([10])

result = np.concatenate((A,B))

print(result)

print(np.unique(result, return_counts=True))

[  0.    2.5   5.    7.5  10.   10. ]
(array([  0. ,   2.5,   5. ,   7.5,  10. ]), array([1, 1, 1, 1, 2], dtype=int64))


In [20]:
A = np.random.randint(10, size=(3, 3))
B = np.random.randint(10, size=(3, 3))
# print(A)
# print(B)

print(np.concatenate([A, B], axis=0))
print(np.concatenate([A, B], axis=1))

[[6 6 7]
 [0 2 5]
 [4 9 3]
 [7 8 6]
 [1 7 5]
 [8 0 0]]
[[6 6 7 7 8 6]
 [0 2 5 1 7 5]
 [4 9 3 8 0 0]]


In [37]:
A = np.linspace(0, 10, 5)
print(np.stack((A, A), axis=0))

[[  0.    2.5   5.    7.5  10. ]
 [  0.    2.5   5.    7.5  10. ]]


In [27]:
print(A.max())
print(A.argmax())
print(A.mean())

10.0
4
5.0


In [30]:
print(np.sum(A))
print(np.median(A))
print(np.std(A))
print(np.var(A))

25.0
5.0
3.53553390593
12.5


In [33]:
A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)
print(np.sum(A))
print(np.sum(A, axis=0))
print(np.sum(A, axis=1))

[[1 2 3]
 [3 4 5]]
18
[4 6 8]
[ 6 12]


In [34]:
np.all(A == A)

True

In [39]:
print(A)
np.percentile(A, 25), np.percentile(A, 30)

[  0.    2.5   5.    7.5  10. ]


(2.5, 3.0)

In [40]:
np.exp(A)

array([  1.00000000e+00,   1.21824940e+01,   1.48413159e+02,
         1.80804241e+03,   2.20264658e+04])

In [42]:
np.log(A[A != 0])

array([ 0.91629073,  1.60943791,  2.01490302,  2.30258509])