In [3]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from konlpy.tag import Twitter

import pandas as pd
import pickle

In [21]:
corpus = [
    '문재인,박근혜 사이언스',
    '데이터 사이언스'
]

In [22]:
pos_tagger = Twitter()
def tokenize_pos(doc):
    return ["/".join(t) for t in pos_tagger.pos(doc)]

In [23]:
vect = TfidfVectorizer(tokenizer=tokenize_pos)

In [24]:
vect.fit(corpus)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=<function tokenize_pos at 0x0000024BB0D0C378>,
        use_idf=True, vocabulary=None)

In [16]:
vect.transform(corpus).toarray()

array([[ 0.57735027,  0.        ,  0.57735027,  0.57735027,  0.        ],
       [ 0.        ,  0.70710678,  0.        ,  0.        ,  0.70710678]])

In [17]:
tokenize_pos(corpus[0])

['문재인/Noun', ',/Punctuation', '박근혜/Noun']

In [18]:
tokenize_pos(corpus[1])

['데이터/Noun', '사이언스/Noun']

In [20]:
vect.vocabulary_

{',/Punctuation': 0,
 '데이터/Noun': 1,
 '문재인/Noun': 2,
 '박근혜/Noun': 3,
 '사이언스/Noun': 4}

In [25]:
vect.transform(corpus).toarray()

array([[ 0.53404633,  0.        ,  0.53404633,  0.53404633,  0.37997836],
       [ 0.        ,  0.81480247,  0.        ,  0.        ,  0.57973867]])

In [26]:
vect.vocabulary_

{',/Punctuation': 0,
 '데이터/Noun': 1,
 '문재인/Noun': 2,
 '박근혜/Noun': 3,
 '사이언스/Noun': 4}

In [27]:
vect = TfidfVectorizer()

In [28]:
vect.fit(corpus)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [29]:
vect.vocabulary_

{'데이터': 0, '문재인': 1, '박근혜': 2, '사이언스': 3}

In [30]:
vect.transform(corpus).toarray()

array([[ 0.        ,  0.6316672 ,  0.6316672 ,  0.44943642],
       [ 0.81480247,  0.        ,  0.        ,  0.57973867]])