In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,size=(3,4))

In [3]:
arr

array([[8, 4, 5, 5],
       [9, 7, 4, 3],
       [4, 3, 9, 5]])

In [4]:
arr[0]

array([8, 4, 5, 5])

In [5]:
arr[0,1]

4

In [6]:
arr[0,0]

8

In [7]:
arr[0][0]

8

In [11]:
arr[1:,1:]

array([[7, 4, 3],
       [3, 9, 5]])

In [13]:
arr[1:][1:]

array([[4, 3, 9, 5]])

In [14]:
arr[1:]

array([[9, 7, 4, 3],
       [4, 3, 9, 5]])

In [24]:
z = np.zeros((5,3))
z

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [23]:
one = np.ones((3,4))
one

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [25]:
tmp = np.arange(10)

In [26]:
tmp

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(5,10,-1)

array([], dtype=int32)

In [28]:
np.arange(10,5,-1)

array([10,  9,  8,  7,  6])

In [29]:
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])