In [1]:
from ml_config import *

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.norm.html

In [17]:
X = np.array([[2, 3, -2], [3, 5, 6], [2, 4, 3]])
print(X)
X = X.reshape(3, 3)
print(X)

[[ 2  3 -2]
 [ 3  5  6]
 [ 2  4  3]]
[[ 2  3 -2]
 [ 3  5  6]
 [ 2  4  3]]


In [18]:
inv_X = np.linalg.inv(X)
print(inv_X)

[[ 0.69230769  1.30769231 -2.15384615]
 [-0.23076923 -0.76923077  1.38461538]
 [-0.15384615  0.15384615 -0.07692308]]


In [19]:
b = np.array([[-5], [12], [7]])

In [22]:
x = np.dot(inv_X, b)
print(x)

[[-2.84615385]
 [ 1.61538462]
 [ 2.07692308]]


In [25]:
A_x = np.dot(X,x)
print(A_x)
print(b)
print(A_x - b)
# https://datascienceschool.net/view-notebook/148fc57f684c4dc48eeb5048ab0d45f2/


[[-5.]
 [12.]
 [ 7.]]
[[-5]
 [12]
 [ 7]]
[[0.00000000e+00]
 [1.77635684e-15]
 [1.77635684e-15]]


In [32]:
% precision 55

'%.55f'

In [27]:
0.1

0.1000000000000000055511151231257827021181583404541015625

In [30]:
% precision % r

'%r'

In [31]:
0.1

0.1

위와 같은 오차때문에 다음과 같은 계산은 피해야 한다
- 0.1 + 0.2 == 0.3

비교하려면 다음과 같이 해야 한다.
- round(0.1 + 0.2) = round(0.3)

왜 이런 현상이 나오나?
- 컴퓨터는 데이터를 2진형식으로 저장하기 때문에 그렇다
    - 언어의 문제가 아님

만약 행렬의 원소의 편차가 크면 역행렬과의 오차가 커진다

In [51]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
Y = boston.target

A = X[:, :]
B = Y[:]

w, resid, rank, s = np.linalg.lstsq(A, B)
residual = B - np.dot(A, w)
# print(np.linalg.norm(residual)**2)
# print(resid)
print(w)

[-9.16297843e-02  4.86751203e-02 -3.77930006e-03  2.85636751e+00
 -2.88077933e+00  5.92521432e+00 -7.22447929e-03 -9.67995240e-01
  1.70443393e-01 -9.38925373e-03 -3.92425680e-01  1.49832102e-02
 -4.16972624e-01]


69절

In [2]:
A = np.array([[2, -1,0],[-1,2,-1],[0,-1,2]])

In [3]:
np.linalg.det(A)

4.0