In [1]:
from ml_config import *

In [2]:
from sklearn.preprocessing import Binarizer

In [3]:
from sklearn.datasets import load_digits
digits = load_digits()

In [11]:
digits.images[0]

array([[  0.,   0.,   5.,  13.,   9.,   1.,   0.,   0.],
       [  0.,   0.,  13.,  15.,  10.,  15.,   5.,   0.],
       [  0.,   3.,  15.,   2.,   0.,  11.,   8.,   0.],
       [  0.,   4.,  12.,   0.,   0.,   8.,   8.,   0.],
       [  0.,   5.,   8.,   0.,   0.,   9.,   8.,   0.],
       [  0.,   4.,  11.,   0.,   1.,  12.,   7.,   0.],
       [  0.,   2.,  14.,   5.,  10.,  12.,   0.,   0.],
       [  0.,   0.,   6.,  13.,  10.,   0.,   0.,   0.]])

In [7]:
bi = Binarizer(threshold=8)

In [9]:
imgs = bi.transform(digits.images[0])

array([[ 0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.]])

In [41]:
imgs=[]
for each in digits.images:
    tmp = bi.transform(each)
    imgs.append(tmp)

In [45]:
for each in imgs:
    print(each.reshape(1,64))

[[ 0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.
   1.  0.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  1.  0.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  0.  1.  0.  1.  1.
   0.  0.  0.  0.  0.  1.  1.  0.  0.  0.]]
[[ 0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.
   0.  1.  1.  0.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.  0.  1.
   1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.
   0.  0.  0.  0.  0.  1.  1.  1.  0.  0.]]
[[ 0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.
   0.  1.  0.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  1.
   1.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.
   0.  0.  0.  0.  0.  0.  1.  1.  1.  0.]]
[[ 0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  1.  0.  1.  0.  0.  0.  0.  0.
   0.  1.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.
   1.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0. 

   1.  0.  0.  0.  0.  1.  1.  1.  0.  0.]]
[[ 0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  0.
   1.  0.  0.  1.  0.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.  1.
   1.  0.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.  1.  0.  0.  1.
   0.  0.  0.  0.  0.  1.  1.  1.  0.  0.]]
[[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.
   1.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  0.  1.  0.
   0.  1.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.
   0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]]
[[ 0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.
   1.  1.  1.  0.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.  1.  1.
   1.  0.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.  1.  1.  1.  0.
   0.  0.  0.  0.  0.  1.  1.  1.  0.  0.]]
[[ 0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.
   0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  1.  1.
   1.  1. 

   0.  0.  0.  0.  0.  1.  1.  0.  0.  0.]]
[[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.
   0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  1.
   1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  1.  1.  1.  1.
   1.  0.  0.  0.  0.  1.  1.  1.  1.  0.]]
[[ 0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  1.
   1.  0.  1.  1.  0.  0.  0.  1.  1.  0.  1.  1.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  1.  1.  1.
   1.  0.  0.  0.  0.  1.  1.  1.  1.  0.]]
[[ 0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  1.
   1.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.
   1.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  1.
   0.  0.  0.  0.  0.  1.  1.  1.  0.  0.]]
[[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.
   1.  1.  0.  1.  0.  0.  0.  0.  1.  0.  1.  0.  0.  0.  0.  1.  1.  0.
   1.  0. 

   0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]]
[[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.
   1.  1.  1.  1.  0.  0.  0.  0.  1.  0.  1.  0.  0.  0.  0.  1.  1.  0.
   1.  1.  1.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.
   0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.
   1.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  1.  0.
   0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  0.  0.  0.  0.  1.  0.  0.
   1.  0.  0.  0.  0.  0.  1.  1.  1.  0.]]
[[ 0.  0.  0.  1.  1.  1.  0.  0.  0.  1.  1.  1.  1.  1.  0.  0.  0.  0.
   0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.
   0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  1.  1.
   1.  0.  0.  0.  0.  1.  1.  0.  0.  0.]]
[[ 0.  0.  1.  1.  1.  1.  0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.
   1.  1.  1.  0.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.  1.  1.
   1.  0. 

   0.  0.  0.  0.  1.  1.  1.  0.  0.  0.]]
[[ 0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  1.
   1.  1.  0.  0.  0.  0.  1.  1.  0.  0.  1.  0.  0.  0.  1.  1.  0.  1.
   1.  0.  0.  0.  0.  1.  1.  1.  0.  0.]]
[[ 0.  0.  1.  1.  1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.
   0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  1.  1.  1.  1.  0.  0.]]
[[ 0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  0.
   1.  0.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  1.  0.  0.  1.
   0.  0.  0.  0.  0.  1.  1.  0.  0.  0.]]
[[ 0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  0.
   1.  0.  0.  1.  0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.
   1.  1. 

   1.  0.  0.  0.  0.  1.  1.  1.  1.  0.]]
[[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  1.  1.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.  0.  1.
   1.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.
   0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]]
[[ 0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  1.  1.  0.  1.  0.  0.  0.  0.
   1.  1.  0.  1.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.  1.  1.
   1.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.
   1.  0.  0.  0.  0.  1.  1.  1.  0.  0.]]
[[ 0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.
   0.  1.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  1.
   1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.
   0.  0.  0.  0.  0.  1.  1.  0.  0.  0.]]
[[ 0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.
   1.  1.  0.  0.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.  1.  0.
   1.  1. 

[[ 0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  1.  1.
   1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  1.
   0.  0.  0.  0.  0.  1.  1.  0.  0.  0.]]
[[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.
   1.  1.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.  1.  1.
   1.  1.  1.  0.  0.  0.  1.  0.  0.  0.  1.  0.  0.  0.  1.  1.  0.  0.
   1.  0.  0.  0.  0.  1.  1.  1.  0.  0.]]
[[ 0.  0.  1.  1.  1.  1.  0.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  0.
   0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  1.
   1.  1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.
   0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.
   1.  1.  0.  1.  0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.  1.  1.
   1.  0.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0. 

[[ 0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.
   0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  1.
   1.  1.  1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.
   0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]]
[[ 0.  0.  1.  1.  0.  0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.  0.
   0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.
   1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.
   1.  0.  0.  0.  1.  1.  1.  1.  1.  0.]]
[[ 0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  1.  1.  1.  1.  1.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  1.  0.  0.  0.  0.  0.  0.
   1.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  1.  0.  1.
   0.  0.  0.  0.  0.  1.  1.  0.  0.  0.]]
[[ 0.  0.  1.  1.  1.  0.  0.  0.  0.  0.  1.  0.  1.  1.  0.  0.  0.  0.
   1.  0.  1.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0. 

[[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.
   1.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  1.
   0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.  1.  1.  1.  1.
   0.  0.  0.  0.  0.  1.  1.  0.  0.  0.]]
[[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.
   1.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  1.  1.
   1.  1.  0.  0.  0.  0.  1.  1.  0.  1.  0.  0.  0.  0.  1.  1.  0.  1.
   1.  0.  0.  0.  0.  1.  1.  1.  0.  0.]]
[[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.
   0.  0.  0.  0.  0.  0.  1.  0.  1.  1.  0.  0.  0.  0.  1.  1.  0.  1.
   1.  0.  0.  0.  0.  1.  1.  1.  0.  0.]]
[[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.
   0.  1.  1.  0.  0.  0.  0.  0.  0.  1.  0.  1.  1.  0.  0.  0.  1.  1.
   1.  1.  0.  0.  0.  1.  1.  1.  1.  1.  0.  0.  0. 

In [46]:
tmp = np.array([each.reshape(1,64)[0] for each in imgs])

In [18]:
imgs = np.array(imgs)

In [28]:
y = np.array([[each] for each in digits.target])

In [21]:
y = digits.target

In [35]:
imgs[0].reshape(1,64)

array([[ 0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,
         1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,
         1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.]])

In [39]:
ximgs = np.array([[each.reshape(1,64)] for each in imgs[0]])

In [48]:
from sklearn.naive_bayes import BernoulliNB
model_bern = BernoulliNB().fit(tmp, y)

d:\anaconda\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [51]:
len(model_bern.predict_proba(tmp))

1797