In [1]:
from ml_config import *

In [6]:
from sklearn.datasets import load_iris
iris = load_iris()

In [65]:
X= iris.data
y= iris.target

In [67]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [112]:
Xtraining = np.concatenate((X[:35], X[50:85], X[100:135]))
Xtest = np.concatenate((X[35:50],X[85:100],X[135:150]))
ytraining = np.concatenate((y[:35] , y[50:85], y[100:135]))
ytest = np.concatenate((y[35:50] , y[85:100], y[135:150]))

In [137]:
from sklearn.naive_bayes import GaussianNB
clf_norm = GaussianNB().fit(X,y)

In [138]:
clf_norm.classes_

array([0, 1, 2])

In [139]:
clf_norm.class_count_

array([ 50.,  50.,  50.])

In [140]:
clf_norm.class_prior_

array([ 0.33333333,  0.33333333,  0.33333333])

In [141]:
clf_norm.theta_

array([[ 5.006,  3.418,  1.464,  0.244],
       [ 5.936,  2.77 ,  4.26 ,  1.326],
       [ 6.588,  2.974,  5.552,  2.026]])

In [142]:
clf_norm.sigma_

array([[ 0.121764,  0.142276,  0.029504,  0.011264],
       [ 0.261104,  0.0965  ,  0.2164  ,  0.038324],
       [ 0.396256,  0.101924,  0.298496,  0.073924]])

In [143]:
y_pred = clf_norm.predict_proba(Xtest)

In [146]:
from sklearn.preprocessing import Binarizer
y_pred

array([[  1.00000000e+000,   1.31355747e-018,   2.91614269e-026],
       [  1.00000000e+000,   3.69675482e-018,   2.51866027e-025],
       [  1.00000000e+000,   3.20344249e-018,   1.12989524e-025],
       [  1.00000000e+000,   2.08944813e-018,   3.09410939e-026],
       [  1.00000000e+000,   9.57268514e-018,   4.26475768e-025],
       [  1.00000000e+000,   6.37746927e-018,   1.99216264e-025],
       [  1.00000000e+000,   7.48755609e-016,   1.85220582e-024],
       [  1.00000000e+000,   6.74316102e-019,   1.54533175e-026],
       [  1.00000000e+000,   6.24456357e-011,   1.54295833e-018],
       [  1.00000000e+000,   8.14548341e-013,   7.52199540e-020],
       [  1.00000000e+000,   1.94244394e-016,   1.96296487e-024],
       [  1.00000000e+000,   2.39642309e-018,   3.11909164e-025],
       [  1.00000000e+000,   2.30047669e-018,   5.36192288e-026],
       [  1.00000000e+000,   2.70414239e-018,   2.86492790e-025],
       [  1.00000000e+000,   3.60099614e-018,   1.12304319e-025],
       [  

In [147]:
bi = Binarizer(threshold=0.8)
y_pred = bi.transform(y_pred)

In [150]:
y_true

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [151]:
y_pred

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.

In [152]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()

In [154]:
lb.fit(y)

LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)

In [157]:
y_pred=lb.inverse_transform(y_pred)

In [159]:
confusion_matrix(y_true,y_pred)

array([[15,  0,  0],
       [ 1, 14,  0],
       [ 0,  0, 15]], dtype=int64)

In [162]:
from sklearn.metrics import *
print(classification_report(y_true, y_pred))

             precision    recall  f1-score   support

          0       0.94      1.00      0.97        15
          1       1.00      0.93      0.97        15
          2       1.00      1.00      1.00        15

avg / total       0.98      0.98      0.98        45



In [165]:
from sklearn.metrics import roc_curve
fpr1, tpr1, thresholds1 = roc_curve(y, clf_norm.predict_proba(X))

ValueError: multiclass format is not supported