In [1]:
%matplotlib inline

In [2]:
from ml_config import *

/home/ej/anaconda3/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [3]:
x = np.array([1, 2, 3])
y = np.array([2, 3, 4])

np.dot(x,y)
np.dot(x.T,y)

20

In [4]:
n = np.array([3, 4, 5])
p = np.array([100, 80, 50])

total_price = np.dot(n, p)

print(total_price)
# 코딩 폰트 설정할 것
# 글자가 동일한 스페이스를 가지는 모노 스페이스 폰트 패밀리로 설정
# http://pinkwink.kr/1039

870


In [5]:
n.mean()

4.0

In [7]:
# 1번
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

B = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
])
print(np.dot(A, B))

[[22 28]
 [49 64]]


In [8]:
# 2번
print(np.dot(B, A))

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [15]:
# 3번
# AB는 되지만 BA는 안됨
A = np.array([1, 2, 3])
B = np.array([
    [4, 7],
    [5, 8],
    [6, 9],
])

print(np.dot(A, B))

[32 50]


In [16]:
# 4번
# 둘 다 가능
A = np.array([
    [1, 2],
    [3, 4],
])

B = np.array([
    [5, 6],
    [7, 8],
])

print(np.dot(A, B))
print(np.dot(B, A))

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [46]:
x = np.array([[1], [2], [3]])
# 원래 이렇게 하는게 맞음

print(x)
print(x.T)

print(np.dot(x.T, x)[0, 0])
# Sum of Square = SS

print(np.dot(x, x.T))

[[1]
 [2]
 [3]]
[[1 2 3]]
14
[[1 2 3]
 [2 4 6]
 [3 6 9]]
